# Generated by Django 4.1.7 on 2023-03-05 07:04

from django.db import migrations, models
import django.db.models.deletion
import users_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.FileField(upload_to=users_auth.models.member_picture_directory_path),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_code', models.TextField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users_auth.member')),
            ],
        ),
    ]
