# Generated by Django 4.1.7 on 2023-03-05 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users_auth", "0002_alter_member_picture_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
